version: "3.2"
services:
  traefik:
    image: traefik:v2.10.0
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/traefik:/etc/traefik
    networks:
      - traefik_proxy
    deploy:
      placement:
        constraints:
          - node.role == manager
      #labels:
      #  - traefik.enable=true
      #  - traefik.http.routers.traefik.rule=Host(`traefik.pnt.home`)
      #   - traefik.http.routers.traefik.service=api@internal
      #  - traefik.http.services.traefik.loadbalancer.server.port=8080
      #  - traefik.http.routers.traefik.entrypoints=web
        
networks:
  traefik_proxy:
    external: true
