[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:$apr1$NAtU/HDE$0BS2zZrg7Dz4N8Tx6M51E1"
  ]
  
[http.routers.api]
  rule = "Host(`traefik.pnt-life.com`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "letsencrypt"
